<?php
// +----------------------------------------------------------------------
// | 平台端菜单设置
// +----------------------------------------------------------------------
return [
    [
        'name' => 'INDEX_ROOT',
        'title' => '概况',
        'url' => 'supply://supply/index/index',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_survey.png',
        'picture_selected' => '',
        'sort' => 1,
    ],
    [
        'name' => 'SUPPLY_ROOT',
        'title' => '供应商',
        'url' => 'supply://supply/supply/config',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_shop.png',
        'picture_selected' => 'addon/supply/supply/view/public/img/menu_icon/menu_shop_selected.png',
        'sort' => 2,
        'child_list' => [
            [
                'name' => 'SUPPLY_MANAGE',
                'title' => '供应商信息',
                'url' => 'supply://supply/supply/config',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/shop.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/shop.png',
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'SUPPLY_CONFIG',
                        'title' => '供应商信息',
                        'url' => 'supply://supply/supply/config',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'SUPPLY_CONTACT',
                        'title' => '联系地址',
                        'url' => 'supply://supply/supply/contact',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 2,
                    ],
                    [
                        'name' => 'SUPPLY_CERT',
                        'title' => '认证信息',
                        'url' => 'supply://supply/supply/cert',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 4,
                    ],
                    [
                        'name' => 'SUPPLY_SERVICE',
                        'title' => '服务保障',
                        'url' => 'supply://supply/services/lists',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 5,
                        'child_list' => [
                            [
                                'name' => 'SUPPLY_SERVICE_APPLY',
                                'title' => '申请服务',
                                'url' => 'supply://supply/services/apply',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'SUPPLY_SERVICE_QUIT',
                                'title' => '退出服务',
                                'url' => 'supply://supply/services/quit',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 2,
                            ],

                        ]
                    ],

                ]
            ],
        ]
    ],
    [
        'name' => 'GOODS_ROOT',
        'title' => '商品',
        'url' => 'supply://supply/goods/lists',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_commodity.png',
        'picture_selected' => 'addon/supply/supply/view/public/img/menu_icon/menu_commodity_selected.png',
        'sort' => 3,
        'child_list' => [
            [
                'name' => 'GOODS_MANAGE',
                'title' => '商品列表',
                'url' => 'supply://supply/goods/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/goods_list.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/goods_list.png',
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'PHYSICAL_GOODS_ADD',
                        'title' => '发布商品',
                        'url' => 'supply://supply/goods/addgoods',
                        'sort' => 5,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'PHYSICAL_GOODS_EDIT',
                        'title' => '编辑商品',
                        'url' => 'supply://supply/goods/editgoods',
                        'sort' => 6,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'VIRTUAL_GOODS_ADD',
                        'title' => '发布商品',
                        'url' => 'supply://supply/virtualgoods/addgoods',
                        'sort' => 5,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'VIRTUAL_GOODS_EDIT',
                        'title' => '编辑商品',
                        'url' => 'supply://supply/virtualgoods/editgoods',
                        'sort' => 6,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_OFF',
                        'title' => '商品下架',
                        'url' => 'supply://supply/goods/offgoods',
                        'sort' => 7,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_ON',
                        'title' => '商品上架',
                        'url' => 'supply://supply/goods/ongoods',
                        'sort' => 8,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_DELETE',
                        'title' => '商品删除',
                        'url' => 'supply://supply/goods/deletegoods',
                        'sort' => 9,
                        'is_show' => 0
                    ],
                ]
            ], [
                'name' => 'PHYSICAL_GOODS_RECYCLE',
                'title' => '回收站',
                'url' => 'supply://supply/goods/recycle',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/recycle.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/recycle.png',
                'sort' => 2,
                'child_list' => [
                    [
                        'name' => 'PHYSICAL_GOODS_RECYCLE_DELETE',
                        'title' => '回收站删除',
                        'url' => 'supply://supply/goods/deleterecycle',
                        'sort' => 1,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'PHYSICAL_GOODS_RECYCLE_RECOVERY',
                        'title' => '回收站恢复',
                        'url' => 'supply://supply/goods/recoveryrecycle',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                ]
            ],
            [
                'name' => 'GOODS_BRAND_MANAGE',
                'title' => '品牌管理',
                'url' => 'supply://supply/goodsbrand/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/brand.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/brand.png',
                'sort' => 3,
                'child_list' => [
                    [
                        'name' => 'GOODS_BRAND_ADD',
                        'title' => '品牌添加',
                        'url' => 'supply://supply/goodsbrand/addbrand',
                        'sort' => 3,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_BRAND_EDIT',
                        'title' => '品牌编辑',
                        'url' => 'supply://supply/goodsbrand/editbrand',
                        'sort' => 4,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_BRAND_DEL',
                        'title' => '品牌删除',
                        'url' => 'supply://supply/goodsbrand/deletebrand',
                        'sort' => 5,
                        'is_show' => 0
                    ]

                ]
            ],
            [
                'name' => 'GOODS_ATTR',
                'title' => '商品类型',
                'url' => 'supply://supply/goodsattr/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/goods.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/goods.png',
                'sort' => 4,
                'child_list' => [
                    [
                        'name' => 'GOODS_ATTR_EDIT',
                        'title' => '类型编辑',
                        'url' => 'supply://supply/goodsattr/editattr',
                        'is_show' => 0
                    ],
                    [
                        'name' => 'GOODS_ATTR_DEL',
                        'title' => '类型删除',
                        'url' => 'supply://supply/goodsattr/deleteattr',
                        'is_show' => 0
                    ]
                ]
            ],

            [
                'name' => 'GOODS_EVALUATE',
                'title' => '商品评价',
                'url' => 'supply://supply/goods/evaluate',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/goods_evaluate.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/goods_evaluate.png',
                'sort' => 6,
                'child_list' => [
                    [
                        'name' => 'GOODS_EVALUATE_DELETE',
                        'title' => '删除',
                        'url' => 'supply://supply/goods/deleteevaluate',
                        'sort' => 1,
                        'is_show' => 0
                    ],
                ]
            ],
            [
                'name' => 'ALBUM_MANAGE',
                'title' => '相册管理',
                'url' => 'supply://supply/album/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/picture.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/picture.png',
                'sort' => 7,
                'child_list' => [
                    [
                        'name' => 'ALBUM_ADD',
                        'title' => '添加相册分组',
                        'url' => 'supply://supply/album/addalbum',
                        'sort' => 1,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_EDIT',
                        'title' => '编辑相册分组',
                        'url' => 'supply://supply/album/editalbum',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_DELETE',
                        'title' => '删除相册分组',
                        'url' => 'supply://supply/album/deletealbum',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_PIC_MODIFY_PICNAME',
                        'title' => '编辑文件名称',
                        'url' => 'supply://supply/album/modifypicname',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_PIC_MODIFY_ALBUM',
                        'title' => '修改文件分组',
                        'url' => 'supply://supply/album/modifyfilealbum',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_PIC_DELETE',
                        'title' => '删除文件',
                        'url' => 'supply://supply/album/deletefile',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                    [
                        'name' => 'ALBUM_BOX',
                        'title' => '相册',
                        'url' => 'supply://supply/album/album',
                        'sort' => 2,
                        'is_show' => 0
                    ],
                ]
            ],
        ]
    ],

    [
        'name' => 'PURCHASE_INDEX',
        'title' => '求购单',
        'url' => 'supply://supply/purchase/lists',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'sort' => 2,
        'child_list' => [
            [
                'name' => 'PURCHASE_LISTS',
                'title' => '求购单列表',
                'url' => 'supply://supply/purchase/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'PURCHASE_DETAIL',
                        'title' => '求购单详情',
                        'url' => 'supply://supply/purchase/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'sort' => 1,
                    ],
                ]
            ],
        ]
    ],

    [
        'name' => 'ORDER_ROOT',
        'title' => '订单',
        'url' => 'supply://supply/order/lists',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_order.png',
        'picture_selected' => '',
        'sort' => 4,
        'child_list' => [
            [
                'name' => 'ORDER_MANAGE',
                'title' => '订单管理',
                'url' => 'supply://supply/order/lists',
                'parent' => '',
                'is_show' => 1,
                'is_control' => 0,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/order.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/order.png',
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'EXPRESS_ORDER_DETAIL',
                        'title' => '订单详情',
                        'url' => 'supply://supply/order/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'EXPRESS_ORDER_CLOSE',
                        'title' => '订单关闭',
                        'url' => 'supply://supply/order/close',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'EXPRESS_ORDER_DELIVER',
                        'title' => '订单发货',
                        'url' => 'supply://supply/order/deliver',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'EXPRESS_ORDER_ADJUST_PRICE',
                        'title' => '订单调价',
                        'url' => 'supply://supply/order/adjustprice',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'EXPRESS_ORDER_EDIT_ADDRESS',
                        'title' => '订单修改收货地址',
                        'url' => 'supply://supply/order/editaddress',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'LOCAL_ORDER_DETAIL',
                        'title' => '外卖订单详情',
                        'url' => 'supply://supply/localorder/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'LOCAL_ORDER_DELIVER',
                        'title' => '外卖订单发货',
                        'url' => 'supply://supply/localorder/deliver',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'STORE_ORDER_DETAIL',
                        'title' => '自提订单详情',
                        'url' => 'supply://supply/storeorder/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'VIRTUAL_ORDER_DETAIL',
                        'title' => '虚拟订单详情',
                        'url' => 'supply://supply/virtualorder/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ]
                ],
            ],
            [
                'name' => 'ORDER_REFUND_LIST',
                'title' => '退款维权',
                'url' => 'supply://supply/orderrefund/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/refund.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/refund.png',
                'sort' => 3,
                'child_list' => [
                    [
                        'name' => 'ORDER_REFUND_DETAIL',
                        'title' => '维权详情',
                        'url' => 'supply://supply/orderrefund/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'ORDER_REFUND_REFUSE',
                        'title' => '维权拒绝',
                        'url' => 'supply://supply/orderrefund/refuse',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'ORDER_REFUND_AGREE',
                        'title' => '维权同意',
                        'url' => 'supply://supply/orderrefund/agree',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'ORDER_REFUND_AGREE',
                        'title' => '维权收货',
                        'url' => 'supply://supply/orderrefund/receive',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'ORDER_REFUND_COMPLETE',
                        'title' => '维权通过',
                        'url' => 'supply://supply/orderrefund/complete',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                ]
            ],

        ]
    ],
    [
        'name' => 'ACCOUNT_ROOT',
        'title' => '资产',
        'url' => 'supply://supply/account/dashboard',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 1,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_account.png',
        'picture_selected' => '',
        'sort' => 8,
        'child_list' => [
            [
                'name' => 'ACCOUNT_DASHBOARD_INDEX',
                'title' => '资产概况',
                'url' => 'supply://supply/account/dashboard',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/money.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/money.png',
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'ACCOUNT_ORDERLIST',
                        'title' => '交易记录',
                        'url' => 'supply://supply/account/orderlist',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                ]
            ],
            [
                'name' => 'SUPPLY_WITHDRAW',
                'title' => '提现记录',
                'url' => 'supply://supply/supplywithdraw/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/shop_withdraw.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/shop_withdraw.png',
                'sort' => 2,
                'child_list' => [
                    [
                        'name' => 'SUPPLY_WITHDRAW_APPLY',
                        'title' => '申请提现',
                        'url' => 'supply://supply/supplywithdraw/apply',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                ]
            ],
            [
                'name' => 'ACCOUNT_OPEN_ACCOUNT',
                'title' => '入驻费用',
                'url' => 'supply://supply/account/openaccount',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/fee.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/fee.png',
                'sort' => 3,
                'child_list' => [
                    [
                        'name' => 'SUPPLY_REOPEN_ADD',
                        'title' => '申请续签',
                        'url' => 'supply://supply/cert/reopen',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                    [
                        'name' => 'SUPPLY_AUTH_APPLY',
                        'title' => '申请续签',
                        'url' => 'supply://supply/cert/index',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 2,
                    ],
                    [
                        'name' => 'SUPPLY_REOPEN_EDIT',
                        'title' => '编辑续签',
                        'url' => 'supply://supply/cert/editreopeninfo',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 3,
                    ],
                    [
                        'name' => 'SUPPLY_REOPEN_LIST',
                        'title' => '续签记录',
                        'url' => 'supply://supply/account/reopenlist',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 4,
                    ],

                ]
            ],
            [
                'name' => 'ACCOUNT_SETTLEMENT',
                'title' => '供应商结算',
                'url' => 'supply://supply/settlement/lists',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/settlement.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/settlement.png',
                'sort' => 4,
                'child_list' => [
                    [
                        'name' => 'ACCOUNT_SETTLEMENT_DETAIL',
                        'title' => '结算详情',
                        'url' => 'supply://supply/settlement/detail',
                        'is_show' => 0,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                ]
            ],
        ]
    ],
    [
        'name' => 'STAT_ROOT',
        'title' => '统计',
        'url' => 'supply://supply/stat/supply',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_data.png',
        'picture_selected' => 'addon/supply/supply/view/public/img/menu_icon/menu_data_selected.png',
        'sort' => 9,
        'child_list' => [
            [
                'name' => 'STAT_SUPPLY',
                'title' => '供应商统计',
                'url' => 'supply://supply/stat/supply',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/stat.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/stat.png',
                'sort' => 2,
            ],
            [
                'name' => 'STAT_GOODS',
                'title' => '商品统计',
                'url' => 'supply://supply/stat/goods',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/stat_goods.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/stat_goods.png',
                'sort' => 3,
            ],
            [
                'name' => 'STAT_ORDER',
                'title' => '交易统计',
                'url' => 'supply://supply/stat/order',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/stat_order.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/stat_order.png',
                'sort' => 4,
            ],
        ]
    ],
    [
        'name' => 'SYSTEM_ROOT',
        'title' => '设置',
        'url' => 'supply://supply/delivery/express',
        'parent' => '',
        'is_show' => 1,
        'is_control' => 0,
        'is_icon' => 0,
        'picture' => 'addon/supply/supply/view/public/img/menu_icon/menu_set.png',
        'picture_selected' => 'addon/supply/supply/view/public/img/menu_icon/menu_set_selected.png',
        'sort' => 10,
        'child_list' => [
            [
                'name' => 'SYSTEM_CONFIG',
                'title' => '系统设置',
                'url' => 'supply://supply/delivery/express',
                'is_show' => 1,
                'is_control' => 1,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/sys_config.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/sys_config.png',
                'sort' => 1,
                'child_list' => [
                    [
                        'name' => 'EXPRESS_CONFIG',
                        'title' => '配送设置',
                        'url' => 'supply://supply/delivery/express',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                        'child_list' => [
                            [
                                'name' => 'EXPRESS_COMPANY',
                                'title' => '物流公司',
                                'url' => 'supply://supply/express/expresscompany',
                                'is_show' => 1,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_EXPRESS_STATUS',
                                'title' => '物流开关',
                                'url' => 'supply://supply/delivery/modifyexpressstatus',
                                'is_show' => 1,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_EDIT_PRINT_TEMPLATE',
                                'title' => '运单模板',
                                'url' => 'supply://supply/express/editprinttemplate',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_TEMPLATE',
                                'title' => '运费模板',
                                'url' => 'supply://supply/express/template',
                                'is_show' => 1,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_TEMPLATE_ADD',
                                'title' => '添加运费模板',
                                'url' => 'supply://supply/express/addtemplate',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_TEMPLATE_EDIT',
                                'title' => '编辑运费模板',
                                'url' => 'supply://supply/express/edittemplate',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_TEMPLATE_DELETE',
                                'title' => '删除运费模板',
                                'url' => 'supply://supply/express/deletetemplate',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'EXPRESS_LOCAL',
                                'title' => '编辑外卖配送',
                                'url' => 'supply://supply/local/local',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 10,
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'USER_AUTH',
                'title' => '账户权限',
                'url' => 'supply://supply/user/user',
                'parent' => '',
                'is_show' => 1,
                'is_control' => 0,
                'is_icon' => 0,
                'picture' => 'addon/supply/supply/view/public/img/icon/account.png',
                'picture_selected' => 'addon/supply/supply/view/public/img/icon/account.png',
                'sort' => 7,
                'child_list' => [
                    [
                        'name' => 'USER_LIST',
                        'title' => '用户管理',
                        'url' => 'supply://supply/user/user',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                        'child_list' => [
                            [
                                'name' => 'USER_ADD',
                                'title' => '用户添加',
                                'url' => 'supply://supply/user/adduser',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_EDIT',
                                'title' => '用户编辑',
                                'url' => 'supply://supply/user/edituser',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_DELETE',
                                'title' => '用户删除',
                                'url' => 'supply://supply/user/deleteuser',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_MODIFY_STATUS',
                                'title' => '调整用户状态',
                                'url' => 'supply://supply/user/modifyuserstatus',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                        ]
                    ],
                    [
                        'name' => 'USER_GROUP',
                        'title' => '用户组',
                        'url' => 'supply://supply/user/group',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                        'child_list' => [
                            [
                                'name' => 'USER_GROUP_ADD',
                                'title' => '用户组添加',
                                'url' => 'supply://supply/user/addgroup',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_GROUP_EDIT',
                                'title' => '用户组编辑',
                                'url' => 'supply://supply/user/editgroup',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_GROUP_DELETE',
                                'title' => '用户组删除',
                                'url' => 'supply://supply/user/deletegroup',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                            [
                                'name' => 'USER_GROUP_MODIFY_STATUS',
                                'title' => '调整用户状态',
                                'url' => 'supply://supply/user/modifygroupstatus',
                                'is_show' => 0,
                                'is_control' => 1,
                                'is_icon' => 0,
                                'picture' => '',
                                'picture_selected' => '',
                                'sort' => 1,
                            ],
                        ]
                    ],
                    [
                        'name' => 'USER_LOG',
                        'title' => '用户日志',
                        'url' => 'supply://supply/user/userlog',
                        'is_show' => 1,
                        'is_control' => 1,
                        'is_icon' => 0,
                        'picture' => '',
                        'picture_selected' => '',
                        'sort' => 1,
                    ],
                ]
            ]

        ]
    ]

];
