<?php 
return array (
  'id' => 'int',
  'site_id' => 'int',
  'roomid' => 'int',
  'name' => 'string',
  'cover_img' => 'string',
  'share_img' => 'string',
  'start_time' => 'int',
  'end_time' => 'int',
  'anchor_name' => 'string',
  'goods' => 'string',
  'live_status' => 'string',
  'anchor_img' => 'string',
  'banner' => 'string',
  'audit_status' => 'int',
  'refuse_reason' => 'string',
  'type' => 'int',
  'close_like' => 'int',
  'close_goods' => 'int',
  'close_comment' => 'int',
  'anchor_wechat' => 'string',
  'site_name' => 'string',
  '_pk' => 'id',
  '_autoinc' => 'id',
);