<?php 
return array (
  'template_id' => 'int',
  'site_id' => 'int',
  'site_name' => 'string',
  'template_type' => 'string',
  'template_name' => 'string',
  'title' => 'string',
  'head' => 'int',
  'buy_notes' => 'int',
  'seller_notes' => 'int',
  'buy_name' => 'int',
  'buy_mobile' => 'int',
  'buy_address' => 'int',
  'shop_mobile' => 'int',
  'shop_address' => 'int',
  'shop_qrcode' => 'int',
  'qrcode_url' => 'string',
  'bottom' => 'string',
  'create_time' => 'int',
  'update_time' => 'int',
  '_pk' => 'template_id',
  '_autoinc' => 'template_id',
);