<?php 
return array (
  'apply_id' => 'int',
  'fenxiao_name' => 'string',
  'parent' => 'int',
  'member_id' => 'int',
  'mobile' => 'string',
  'nickname' => 'string',
  'headimg' => 'string',
  'level_id' => 'int',
  'level_name' => 'string',
  'order_complete_money' => 'float',
  'order_complete_num' => 'int',
  'reg_time' => 'int',
  'create_time' => 'int',
  'update_time' => 'int',
  'status' => 'int',
  '_pk' => 'apply_id',
  '_autoinc' => 'apply_id',
);