<?php 
return array (
  'id' => 'int',
  'reopen_no' => 'string',
  'site_id' => 'int',
  'website_id' => 'int',
  'member_id' => 'int',
  'apply_state' => 'int',
  'apply_message' => 'string',
  'apply_year' => 'int',
  'shop_group_name' => 'string',
  'shop_group_id' => 'int',
  'paying_money_certificate' => 'string',
  'paying_amount' => 'float',
  'paying_money_certificate_explain' => 'string',
  'create_time' => 'int',
  'audit_time' => 'int',
  'finish_time' => 'int',
  '_pk' => 'id',
  '_autoinc' => 'id',
);