<?php 
return array (
  'category_id' => 'int',
  'category_name' => 'string',
  'short_name' => 'string',
  'pid' => 'int',
  'level' => 'int',
  'is_show' => 'int',
  'sort' => 'int',
  'image' => 'string',
  'keywords' => 'string',
  'description' => 'string',
  'attr_class_id' => 'int',
  'attr_class_name' => 'string',
  'category_id_1' => 'int',
  'category_id_2' => 'int',
  'category_id_3' => 'int',
  'category_full_name' => 'string',
  'image_adv' => 'string',
  'commission_rate' => 'float',
  '_pk' => 'category_id',
  '_autoinc' => 'category_id',
);