<?php 
return array (
  'period_id' => 'int',
  'period_no' => 'string',
  'shop_num' => 'int',
  'order_money' => 'float',
  'shop_money' => 'float',
  'refund_shop_money' => 'float',
  'platform_money' => 'float',
  'refund_platform_money' => 'float',
  'refund_money' => 'float',
  'period_start_time' => 'int',
  'period_end_time' => 'int',
  'commission' => 'float',
  'create_time' => 'int',
  'website_commission' => 'float',
  'platform_coupon_money' => 'float',
  '_pk' => 'period_id',
  '_autoinc' => 'period_id',
);