<?php 
return array (
  'fenxiao_id' => 'int',
  'fenxiao_no' => 'string',
  'fenxiao_name' => 'string',
  'mobile' => 'string',
  'member_id' => 'int',
  'level_id' => 'int',
  'level_name' => 'string',
  'parent' => 'int',
  'grand_parent' => 'int',
  'account' => 'float',
  'account_withdraw' => 'float',
  'account_withdraw_apply' => 'float',
  'status' => 'int',
  'create_time' => 'int',
  'audit_time' => 'int',
  'lock_time' => 'int',
  'one_fenxiao_order_num' => 'int',
  'one_fenxiao_order_money' => 'float',
  'one_child_num' => 'int',
  'one_child_fenxiao_num' => 'int',
  'two_child_fenxiao_num' => 'int',
  'total_commission' => 'float',
  '_pk' => 'fenxiao_id',
  '_autoinc' => 'fenxiao_id',
);