<?php 
return array (
  'id' => 'int',
  'site_id' => 'int',
  'year' => 'int',
  'month' => 'int',
  'day' => 'int',
  'day_time' => 'int',
  'order_total' => 'float',
  'shipping_total' => 'float',
  'refund_total' => 'float',
  'order_pay_count' => 'int',
  'goods_pay_count' => 'int',
  'shop_money' => 'float',
  'platform_money' => 'float',
  'create_time' => 'int',
  'modify_time' => 'int',
  'collect_shop' => 'int',
  'collect_goods' => 'int',
  'visit_count' => 'int',
  'order_count' => 'int',
  'goods_count' => 'int',
  'add_goods_count' => 'int',
  'member_count' => 'int',
  '_pk' => 'id',
  '_autoinc' => 'id',
);