<?php 
return array (
  'level_id' => 'int',
  'level_num' => 'string',
  'level_name' => 'string',
  'one_rate' => 'float',
  'two_rate' => 'float',
  'three_rate' => 'float',
  'upgrade_type' => 'int',
  'fenxiao_order_num' => 'int',
  'fenxiao_order_meney' => 'float',
  'one_fenxiao_order_num' => 'int',
  'one_fenxiao_order_money' => 'float',
  'order_num' => 'int',
  'order_money' => 'float',
  'child_num' => 'int',
  'child_fenxiao_num' => 'int',
  'one_child_num' => 'int',
  'one_child_fenxiao_num' => 'int',
  'status' => 'int',
  'create_time' => 'int',
  'update_time' => 'int',
  '_pk' => 'level_id',
  '_autoinc' => 'level_id',
);