<?php 
return array (
  'uid' => 'int',
  'app_module' => 'string',
  'app_group' => 'int',
  'is_admin' => 'int',
  'site_id' => 'int',
  'group_id' => 'int',
  'group_name' => 'string',
  'username' => 'string',
  'password' => 'string',
  'member_id' => 'int',
  'create_time' => 'int',
  'update_time' => 'int',
  'status' => 'int',
  'login_time' => 'int',
  'login_ip' => 'string',
  '_pk' => 'uid',
  '_autoinc' => 'uid',
);