<?php 
return array (
  'id' => 'int',
  'app_module' => 'string',
  'addon' => 'string',
  'title' => 'string',
  'name' => 'string',
  'parent' => 'string',
  'level' => 'int',
  'url' => 'string',
  'is_show' => 'int',
  'sort' => 'int',
  'desc' => 'string',
  'is_icon' => 'int',
  'picture' => 'string',
  'picture_select' => 'string',
  'is_control' => 'int',
  '_pk' => 'id',
  '_autoinc' => 'id',
);